//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuma", ReplyAction="http://tempuri.org/IService1/GetSumaResponse")]
        int GetSuma(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuma", ReplyAction="http://tempuri.org/IService1/GetSumaResponse")]
        System.Threading.Tasks.Task<int> GetSumaAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetResta", ReplyAction="http://tempuri.org/IService1/GetRestaResponse")]
        int GetResta(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetResta", ReplyAction="http://tempuri.org/IService1/GetRestaResponse")]
        System.Threading.Tasks.Task<int> GetRestaAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMultiplicacion", ReplyAction="http://tempuri.org/IService1/GetMultiplicacionResponse")]
        int GetMultiplicacion(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMultiplicacion", ReplyAction="http://tempuri.org/IService1/GetMultiplicacionResponse")]
        System.Threading.Tasks.Task<int> GetMultiplicacionAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDivision", ReplyAction="http://tempuri.org/IService1/GetDivisionResponse")]
        int GetDivision(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDivision", ReplyAction="http://tempuri.org/IService1/GetDivisionResponse")]
        System.Threading.Tasks.Task<int> GetDivisionAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Calculadora.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Calculadora.ServiceReference1.IService1>, Calculadora.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSuma(int a, int b) {
            return base.Channel.GetSuma(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetSumaAsync(int a, int b) {
            return base.Channel.GetSumaAsync(a, b);
        }
        
        public int GetResta(int a, int b) {
            return base.Channel.GetResta(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetRestaAsync(int a, int b) {
            return base.Channel.GetRestaAsync(a, b);
        }
        
        public int GetMultiplicacion(int a, int b) {
            return base.Channel.GetMultiplicacion(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetMultiplicacionAsync(int a, int b) {
            return base.Channel.GetMultiplicacionAsync(a, b);
        }
        
        public int GetDivision(int a, int b) {
            return base.Channel.GetDivision(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetDivisionAsync(int a, int b) {
            return base.Channel.GetDivisionAsync(a, b);
        }
    }
}
